include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/injectable.config.dart"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_use_package_imports: true
    avoid_dynamic_calls: true
    unnecessary_await_in_return: true
    use_build_context_synchronously: true
    sort_pub_dependencies: false
