import 'package:clipboard_app/features/tasks/domain/entities/task.dart';
import 'package:clipboard_app/features/tasks/domain/repositories/task_repository.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:injectable/injectable.dart';

@LazySingleton(as: TaskRepository)
class TaskRepositoryImpl implements TaskRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _tasksRef =>
      _firestore.collection('tasks');

  @override
  Stream<List<Task>> getTasks(String? volunteerId) {
    return _tasksRef
        .where('volunteerId', isEqualTo: volunteerId)
        .orderBy('deadline', descending: false)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Task.fromJson({...doc.data(), 'id': doc.id}))
            .toList());
  }

  @override
  Stream<List<Task>> getAllTasks() {
    return _tasksRef
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Task.fromJson({...doc.data(), 'id': doc.id}))
            .toList());
  }

  @override
  Future<void> createTask(Task task) async {
    final data = task.toJson()..remove('id'); // ID is generated by Firestore
    await _tasksRef.add(data);
  }

  @override
  Future<void> updateTaskStatus(String taskId, TaskStatus status) async {
    await _tasksRef.doc(taskId).update({'status': status.name});
  }

  @override
  Future<void> updateTask(Task task) async {
    final data = task.toJson()..remove('id');
    await _tasksRef.doc(task.id).update(data);
  }

  @override
  Future<void> deleteTask(String taskId) async {
    await _tasksRef.doc(taskId).delete();
  }
}
