import 'package:clipboard_app/features/auth/domain/entities/auth_user.dart';
import 'package:clipboard_app/features/auth/presentation/providers/auth_provider.dart';
import 'package:clipboard_app/features/auth/presentation/providers/user_providers.dart';
import 'package:clipboard_app/features/tasks/domain/entities/task.dart';
import 'package:clipboard_app/features/tasks/presentation/providers/task_providers.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

class CreateTaskPage extends HookConsumerWidget {
  const CreateTaskPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final titleController = useTextEditingController();
    final descriptionController = useTextEditingController();
    final deadline = useState<DateTime>(DateTime.now().add(const Duration(days: 7)));
    final selectedVolunteer = useState<AuthUser?>(null);
    final volunteersAsync = ref.watch(volunteersProvider);
    final coordinator = ref.watch(authProvider);

    return Scaffold(
      backgroundColor: const Color(0xFF1A1A2E),
      appBar: AppBar(title: const Text('Create New Task'), backgroundColor: Colors.transparent),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildFieldLabel('Task Title'),
            TextField(
              controller: titleController,
              style: const TextStyle(color: Colors.white),
              decoration: _inputDecoration('Enter task name'),
            ),
            const SizedBox(height: 24),
            _buildFieldLabel('Description'),
            TextField(
              controller: descriptionController,
              maxLines: 3,
              style: const TextStyle(color: Colors.white),
              decoration: _inputDecoration('Enter task details'),
            ),
            const SizedBox(height: 24),
            _buildFieldLabel('Assign Volunteer'),
            volunteersAsync.when(
              data: (volunteers) => DropdownButtonFormField<AuthUser>(
                initialValue: selectedVolunteer.value,
                dropdownColor: const Color(0xFF16213E),
                style: const TextStyle(color: Colors.white),
                decoration: _inputDecoration('Select a volunteer'),
                items: volunteers.map((v) => DropdownMenuItem(
                  value: v,
                  child: Text(v.name),
                )).toList(),
                onChanged: (val) => selectedVolunteer.value = val,
              ),
              loading: () => const CircularProgressIndicator(),
              error: (e, s) => Text('Error loading volunteers: $e', style: const TextStyle(color: Colors.red)),
            ),
            const SizedBox(height: 24),
            _buildFieldLabel('Deadline'),
            InkWell(
              onTap: () async {
                final date = await showDatePicker(
                  context: context,
                  initialDate: deadline.value,
                  firstDate: DateTime.now(),
                  lastDate: DateTime.now().add(const Duration(days: 365)),
                );
                if (date != null) deadline.value = date;
              },
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                decoration: BoxDecoration(
                  color: Colors.white.withValues(alpha: 0.05),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.calendar_today, color: Color(0xFF00D2FF), size: 20),
                    const SizedBox(width: 12),
                    Text(
                      '${deadline.value.day}/${deadline.value.month}/${deadline.value.year}',
                      style: const TextStyle(color: Colors.white, fontSize: 16),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 48),
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton(
                onPressed: () async {
                  if (titleController.text.isEmpty || coordinator == null) return;
                  
                  final task = Task(
                    id: '', // Generated by Firestore
                    title: titleController.text,
                    description: descriptionController.text,
                    coordinatorId: coordinator.id,
                    volunteerId: selectedVolunteer.value?.id,
                    volunteerName: selectedVolunteer.value?.name,
                    status: TaskStatus.pending,
                    deadline: deadline.value,
                    createdAt: DateTime.now(),
                  );
                  
                  await ref.read(taskRepositoryProvider).createTask(task);
                  if (context.mounted) context.pop();
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFE94560),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                ),
                child: const Text('Publish Task', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFieldLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Text(label, style: const TextStyle(color: Colors.white70, fontSize: 14, fontWeight: FontWeight.bold)),
    );
  }

  InputDecoration _inputDecoration(String hint) {
    return InputDecoration(
      hintText: hint,
      hintStyle: const TextStyle(color: Colors.white24),
      filled: true,
      fillColor: Colors.white.withValues(alpha: 0.05),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.white.withValues(alpha: 0.1)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: Color(0xFF00D2FF)),
      ),
    );
  }
}
